
target 'ACFloatingInput_Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  platform :ios, '8.0'
  pod 'ACFloatingInput', :path => '../'

end
