# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ACFloatingInput_Example' do
  pod 'ACFloatingInput', :path => '../'

  target 'ACFloatingInput_Tests' do
    inherit! :search_paths
  end
end
